### ISSUE TITLE
Find a name

### ISSUE THREAD

**Issue by myvertigo** [js-republic/sideral#1]
Sideral is just a code name.
Any idea for the real name of this framework ?
It will be cool if the name is a bit funny or related to the video game.

**Comment by myvertigo** [comment]
We have a Tricider to find the name here : [http://www.tricider.com/admin/3GEvip6W7QV/A6qLbor66Bp](Tricider)

"Slime" seems to be the best name for this framework. What do you think about it ?
in npm Packages, "slime" is not already taken but there is a "slimejs".

For me, i'm ok to set "Slime" as name for this project.

**Comment by mbreton** [comment]
When you will change the name of the project. Don't forget to check each third part tools (like Gitmagic, Continuous Integration, Waffle.io, etc) to check if it handles well the name changing. For example, when I change the name of SGR project to ReDoc project, waffle.io no longer knew the project

**Comment by myvertigo** [comment]
With @baxterio, it was concluded that the codename **Sideral** will be the *final name* for this project.
